# Example docker-compose.yml file
version: '2'
services:
  notebooks:
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
    - .:/src/ML_projects
    - .:/notebooks
    - ./archive:/tensorboard
    - /Users/Shuang/GitHub/dataset:/data
    # - /mnt/lab/shuang_data:/data
